FROM --platform=linux/amd64 cgr.dev/chainguard/node:latest AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
COPY tsconfig.base.json tsconfig.demo.json ./
COPY packages ./packages
COPY demo ./demo
RUN npm ci
RUN npm run build

FROM --platform=linux/amd64 cgr.dev/chainguard/node:latest
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
CMD ["node", "packages/core/dist/main.js"]
